Hl fix negative buy
ucsb-cs156-w24/proj-happy-cows-w24-4pm-4 pull request #15
Opened 2024-02-27 23:33 UTC by hongye-liang

## Overview

In this PR, I fixed the bug of allowing users to buy negative amounts of cows. Now users must enter a positive number of cows to buy in order to make a successful purchase (increase the number of cows owned and decrease wealth).

## Screenshots (Optional)
![image](https://github.com/ucsb-cs156-w24/proj-happy-cows-w24-4pm-4/assets/97082279/9889ba26-69c8-4696-9f74-394d9ab68895)

## Tests

- [ ] Backend Unit tests (`mvn test`) pass
- [ ] Backend Test coverage (`mvn test jacoco:report`) 100%
- [ ] Backend Mutation tests (`mvn test pitest:mutationCoverage`) 100% 
- [ ] Frontend Unit tests (`npm test`) pass
- [ ] Frontend Test coverage (`npm run coverage`) 100%
- [ ] Frontend Mutation tests (`npx stryker run`) 100% 
- [ ] Frontend Linting (`npx eslint --fix src`) 

## Linked Issues

Closes #8

2024-02-28 11:47 UTC, hyi96 approved these changes, later dismissed
lgtm.

2024-02-28 21:40 UTC, AnikaArora requested changes
The code looks good, but please remove all the extra non-essential comments (ex: "//new added") that you added. It helps the code look cleaner in the end!

2024-02-28 22:15 UTC, hongye-liang commented
OK! Everything should be removed now.

2024-02-29 00:51 UTC, AnikaArora approved these changes

2024-02-29 00:52 UTC, anguyen412 approved these changes

2024-02-29 00:58 UTC, merged